baseURL = 'https://danhumassmed.github.io/C4W-Blog/'
languageCode = 'en-us'
title = 'C4W Blog'
theme = "hugo-xmag"

[params.banner]
    src = "images/C4W-logo.png"
    alt = "Code for Worcester"


[params]
	description = "Civic Innovation in Worcester"

[taxonomies]
  tag = "tags"
  category = "categories"

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1


  [[menu.main]]
    name = "Categories"
    url = "categories/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "tags/"
    weight = 3
	
  [[menu.main]]
    name = "Blog"
    url = "post/"
    weight = 4